### ISSUE TITLE
El Capitan volume not booting (iMac 5,1)

### ISSUE THREAD

**Issue by cabalex** [rmc-team/osx-patcher#22]
Hello!
First off, I just wanted to thank you for making this great tool. However, I've run into an issue when setting up El Capitan on my Mac 5,1 (late 2006): it just won't boot the volume that I had set up El Capitan on, despite me installing and patching the OS onto it. (My symptoms sound similar to #20's; I select the El Capitan volume, but it boots my Lion volume instead)
I've tried repatching, reinstalling the OS... no luck.

The only error I could think of during installation was [when running `patch` ](https://github.com/rmc-team/osx-patcher#patch-the-os) in the installation volume. After it patches the kernel cache and repairs permissions, these non-green/blue lines appear:
```
Jan 01 17:46:20 + Patched kernel cache.
Jan 01 17:46:53 > Repairing permissions.
chown: /Volumes/El Capitan/System/Library/Extensions/GeForce7xxxGLDriver.bundle: No such file or directory
chmod: /Volumes/El Capitan/System/Library/Extensions/GeForce7xxxGLDriver.bundle: No such file or directory
              + Repaired permissions.
Jan 01 17:46:54 + Patched Recovery partition.
Jan 01 17:46:56 / Thank you for using OS X Patcher.
```
Even though the patcher seems to exit normally, that's the only lead I can think of.
Is El Capitan too new for my device, and should I downgrade to Yosemite or lower? Is my version of the OS X El Capitan installer broken? Maybe I just made a dumb mistake? I wonder if you can help.
Thanks in advance!

**Comment by julian-fairfax** [comment]
The issue with the patch command should be fixed with [this version](https://github.com/rmc-team/osx-patcher/archive/master.zip). As for the main issue, can you try booting in verbose mode to see where it goes wrong?

**Comment by cabalex** [comment]
That did fix the graphics card error! However, you're right in that it didn't fix the main issue.

As for verbose mode, the last lines before it boots to my old volume look like this (although the full verbose output [looks like this](https://i.imgur.com/xlsQ9IM.png)):
```
macx_swapon SUCCESS
Waiting for DSMOS...
SMC::smcReadKeyAction ERROR: smcReadData8 ailed for key $Num (kSMCKeyNotFound)
SMC::smcReadKeyAction ERROR $Num kSMCKeyNotFound(0x84) fKeyHashTable=0x0
Previous Shutdown Cause: 0
SMC::smcInitHelper ERROR: MMIO regMap == NULL - fall back to old SMC mode
DSMOS has arrived
SMC::smcReadKeyAction ERROR: smcReadData8 failed for key BEMB (kSMCKeyNotFound)
AirPort: Link Down on en1. Reason 1 (Unspecified).
```

**Comment by julian-fairfax** [comment]
Yeah unfortunately there's nothing useful in that. You could try installing another version but I honestly don't know what the issue is. Sorry.

**Comment by cabalex** [comment]
I tried installing Yosemite too... no luck there either. I'm not really sure what else I can troubleshoot... I guess I'll look elsewhere for patching tools.
Thanks for the help and the useful tool though! It was very easy to follow disregarding my Mac's shenanigans.

**Comment by julian-fairfax** [comment]
Sorry I couldn't help you more
